### ISSUE TITLE
We are creating too much work for ourselves

### ISSUE THREAD

**Issue by w-shackleton** [WildPetScience/Specification#15]
Discuss. I think we are currently on the edge of doing this, but at the moment OK.

I do fear that the client will list lots of wonderful extra features in the meeting next week.

**Comment by Baltoli** [comment]
I think as it stands we're ok - we can negotiate with the client if he wants to add a huge amount more to it I think.

**Comment by w-shackleton** [comment]
:+1:

**Comment by rogersnm** [comment]
> Migration Patterns
> 
> The data should also be used to determine the movement of the animal during some timeframe (for example: last hour, last 24 hours, etc.). **As the visualisation of this data is would be done by superimposing the migration pattern on a still image of the cage, this feature would only be available on the client software.**

Is the extra work the emphasised statement entails demanded by the brief?

**Comment by w-shackleton** [comment]
No, but it gets us points in terms of child protection - we can't ever transmit images to the server in case they contain kids etc.

**Comment by w-shackleton** [comment]
I think we are good on this.
