### ISSUE TITLE
We want to use a public ID to view data and not have authentication

### ISSUE THREAD

**Issue by w-shackleton** [WildPetScience/Specification#19]
Remove the specification of using Google accounts, switch to public / private API key design.

**Comment by rogersnm** [comment]
Not sure about this, I don't think user accounts will be any more difficult to implement and the sense of ownership they can bring to the end-user/child may be beneficial

**Comment by Baltoli** [comment]
I think that adding user accounts is a fairly orthogonal issue to the project - having a key still means that users can see "their" data, it just makes our lives a lot easier implementing things.

**Comment by rogersnm** [comment]
I don't necessaarily agree that user accounts are an orthogonal issue given the limited brief we had..

> Children should be able to use the data they collect to
> make comparisons between their own pets and wild animals

Whilst a key would facilitate this comparison, it's not really child friendly.

**Comment by Baltoli** [comment]
Decided to use a public ID in the interests of effort and time.
