### ISSUE TITLE
Client -> Movement Tracking

### ISSUE THREAD

**Issue by rogersnm** [WildPetScience/Specification#22]
> Movement Tracking
> 
> The stream of images provided through the capture interface will be analysed by a motion tracker in order to detect the position (XY coordinates) of the animal in each image. **This data will be in turn used to determine what the animal was doing at a given time.**

The meaning of the emphasised statement is vague... what do we mean by being able to tell what the animal is doing?

**Comment by w-shackleton** [comment]
Zones - I'll fix now
